Branch of changes
Demiurgosan/Pt_1 pull request #1
Opened 2022-11-23 22:19 UTC by Demiurgosan

Update

2022-11-25 07:49 UTC, DanMagor requested changes

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/CameraFollow.cs
> +    [SerializeField] private Transform _target;
здесь пока непонятно как таргет использоется, но ок

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/Controls.cs
> +    private float _tergetX;
опечатка в нейминге, если это target

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/HpStack.cs
> +    public GameObject HpPrefab;
возможно тут тоже можно заменить на SerializeField? Оба поля? Или они где-то используются?

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/HpStack.cs
> +    private List<GameObject> _cubesList = new List<GameObject>();// do i need <T> GameObject or Transform?
Можно и GameObject, можно и трансформ, смотря что тебе нужно. Ты и то и друго юзаешь вроде

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +        if(GizmoIsActive == true)
тут можешь не так писать. Во первых if (GizmoIsActive == true) - это тоже самое что и if (GizmoIsActive)
Результат выражения GizmoIsActive==true возвращает bool, либо true, либо false, но GizmoIsActive само по себе true или false. В общем, сравнени излишне.
Второе, чтобы уменьшить вложенность, ты можешь просто сделать if (!GizmoIsActive) return; Тогда не придется тащить скобку if через весь метод

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +        GetComponent<BoxCollider>().size = new Vector3(ColumnsPeak.Length * BrickWidth, maxPeak * BrickHeight * 2, 1.1f);
тут снова Magic Number. Я верно понимаю, что ты решил через размер коллайдера вычислять количество блоков?

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +        foreach (int i in ColumnsPeak) { maxPeak = Math.Max(maxPeak, i); }//compute posible maximum lenght of array's 2nd demention
тут можно использовать LinQ: 
int maxPeak = ColumnsPeak.Max();

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +        /*WallValues = new int[ColumnsPeak.Length];//compute sum of existing bricks in columns
если лишнее, то надо почистить перед пул реквестом

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +                        new Vector3(i * BrickWidth - (ColumnsPeak.Length / 2f - BrickWidth / 2),
тут тоже Magic Numbers

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +                        new Vector3(i * BrickWidth - (ColumnsPeak.Length / 2f - BrickWidth / 2),
А, ну тут понятно почему /2, типа пополам, тогда не Magic Num, все ок)

2022-11-25 07:49 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +        if (collider.TryGetComponent(out Player player))
ну, тут дописывать надо

2022-11-26 22:27 UTC, Demiurgosan commented on Assets/Scripts/Wall.cs
> +        foreach (int i in ColumnsPeak) { maxPeak = Math.Max(maxPeak, i); }//compute posible maximum lenght of array's 2nd demention
Поправил

2022-11-26 22:27 UTC, Demiurgosan commented on Assets/Scripts/CameraFollow.cs
> +    [SerializeField] private Transform _target;
Исправил, в коде не использовалось, а нужно было.

2022-11-26 22:30 UTC, Demiurgosan commented on Assets/Scripts/Controls.cs
> +    private float _tergetX;
нет, не опечатка, это положение по Х куда должен сдвинуться игрок.

2022-11-26 22:31 UTC, Demiurgosan commented on Assets/Scripts/HpStack.cs
> +    public GameObject HpPrefab;
Исправил

2022-11-26 22:31 UTC, Demiurgosan commented on Assets/Scripts/Wall.cs
> +        if(GizmoIsActive == true)
Сделал

2022-11-26 22:49 UTC, Demiurgosan commented on Assets/Scripts/Wall.cs
> +        GetComponent<BoxCollider>().size = new Vector3(ColumnsPeak.Length * BrickWidth, maxPeak * BrickHeight * 2, 1.1f);
наоборот. через кол-во блоков расчитать размер. "2" здесь чтобы покрыть весь объем, "1.1" по Z чтобы коллайдер немного выпирал за границы кубиков. Всё равно переделать их в переменные?

2022-11-30 11:59 UTC, merged