Core mechanics and sample of levels
Demiurgosan/Pt_1 pull request #2
Opened 2022-12-09 14:06 UTC by Demiurgosan

2022-12-12 13:52 UTC, DanMagor requested changes

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Controls.cs
> +    [HideInInspector] public bool IsFall = false;
Почему тут Public и спрятано в инспекторе? Если это чисто внутреннее поле, то надо Private, наверное?

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Controls.cs
> +    public float FallingSpeed = 1;
Тоже Public вместо SerializeField

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Controls.cs
> +            transform.position = new Vector3(transform.position.x, transform.position.y - FallingSpeed * Time.deltaTime, transform.position.z);
просто чтобы лучше читалось, я бы тут разбил на две строчки - где Y считаешь и отдельно где присваиваешь новый вектор, но это не крит. А вообще, ты здесь можешь еще сократить:

```
var targetY = transform.position.y - FallingSpeed * Time.deltaTime;
transform.position = transform.position + new Vector3(0, targetY, 0);
```

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Controls.cs
> +            transform.position = new Vector3(transform.position.x, transform.position.y - FallingSpeed * Time.deltaTime, transform.position.z);
Просто лаконичнее получается по читаемости

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Controls.cs
> +            if (transform.position.y < 0)
на всякий случай делал бы <=0

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Controls.cs
>      private void FixedUpdate()
Вообще, меня смущает, что ты движение вбок и вниз делаешь в Update, а вперед в FixedUpdate. Ты же физику не используешь. Значит тебе только Update нужен

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Game.cs
>  public class Game : MonoBehaviour
Имя класса не совсем соответствует его задачам сейчас. Если он просто за показ экрана отвечает, то соответственно и назови ScreenManager или типа того

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Lava.cs
> +            player.BumpedInLava();
В данном случае не крит, но мне кажется, что логика должна наоборот происходить.
Смотри, у тебя по сути Lava говорит игроку что он должен делать. А это как бы не совсем верно. Игрок сам должен понять, что он стукнулся в лаву и теперь должен что-то сделать.
Т.е. скрипт Lava можно просто оставить пустым и проверять внутри игрока столкновение. А еще лучше в отдельном классе типа LavaChecker, который тоже висит на игроке и отвечает за одну задачу - проверку столкнулся ли игрок с лавой.

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +    private void OnDrawGizmos()
Желательно вниз помещать этот метод внутри класса. Он дебажный логики не несет и ты меньше всего его хочешь видеть в начале скрипта

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +        int deniedRowsCount = 0;
лучше писать var, если тип понятен

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +            if (_rowsDenied[e] != 0) deniedRowsCount++;}
что-то вообще эту строчку не пойму. e - это ведь буквально цифра внутри массива и ты ее же используешь как индекс. если ты используешь 0 и 1 для идентификации, то, получается, что у тебя e будет обращаться к 0-му или 1-му элементу

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +            if (_rowsDenied[e] != 0) deniedRowsCount++;}
Выглядит как ошибка в логике, в общем

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +        transform.position = new Vector3(transform.position.x, (float)columnBumpedMax, transform.position.z);
Здесь привод к типу (float) излишен вроде как

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +        GetComponent<Controls>().IsFall = true;
Если постоянно обращаешься - то надо захэшировать в поле. А вообще, теперь понятно зачем тебе isFall. Не совсем хорошо из игрока говорить Control, что происходит падение, еще и менять поле в другом классе. Скорее Control должен следить за состоянием игрока и реагировать соответствующим образом. Для этого подойдет либо паттерн Subscriber Observer, либо просто изменение поле внутри Player и в Update Control чекает публичное для чтения поле у игрока.

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +        Game.Win();
Та же ситуация. Это скорее Game должен следить за игроком и запускать себя сам, но это разберем после других правок

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +            Game.Lose();
про Lose Тоже самое, что и Win

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +            _playerCubes[i+cubesCount].transform.position = new Vector3(transform.position.x, i + 0.5f + cubesCount, transform.position.z);
0.5f - magic number.
Лучше разбивать подсчет Y координаты в отдельную строку, чтобы читаемость была выше и не надо было всматриваться в строку что там за операция арифметическая

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Player.cs
> +            _playerCubes.RemoveAt(_playerCubes.Count-1);
Не крит в контексте Unity (наверное), но лучше сначала сохранить ссылку на GameObject, ремовнуть с массива, а потом уничтожить. Не уверен как очистка памяти в таком случае будут работать просто.

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/UI_NextLvl.cs
> +    public void OnBottonClick()
B**u**tton

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/UI_NextLvl.cs
> +public class UI_NextLvl : MonoBehaviour
Нейминг не соответствует стилю кода
UiNextLvl/UINextLevel будет лучше, чем прочерк в имени класса

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/UI_NextLvl.cs
> +        if(SceneManager.GetActiveScene().buildIndex == SceneManager.sceneCountInBuildSettings - 1)
Такой себе подход считать количество сцен и отнимать 1, а если количество или порядок изменится?
Просто сделать сериализованное поле и введи туда параметр сцены, если уж на то пошло. А вообще, у тебя уровни на сценах сделаны?

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/UI_Restart.cs
> +    public void OnBottonClick()
Button

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +            int columnBumpedMax = Mathf.Max(_columnsPeak[bumpedColumn1], _columnsPeak[bumpedColumn2]);
тоже var лучше писать, как и выше

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Wall.cs
>                  else if (player.transform.position.x < _wallPoints[e + 1])
а если игрок правее? Что-то не покрыт это кейс как будто бы

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Wall.cs
>                  else if (player.transform.position.x < _wallPoints[e + 1])
если игрок находится правее предпоследнего (слева на право) кубика, но левее последнего (не уверен, что такое возможно, но все же) или правее самого правого кубика, непонятно что будет с bumperColumn2 - выйдет за пределы как будто бы

2022-12-12 13:52 UTC, DanMagor commented on Assets/Scripts/Wall.cs
> +            player.BumpedInWall(columnBumpedMax, _rowsDenied);
аналогично про то "кто кому что сообщает"

2022-12-13 12:30 UTC, Demiurgosan commented on Assets/Scripts/Controls.cs
> +    public float FallingSpeed = 1;
Исправил

2022-12-13 12:47 UTC, Demiurgosan commented on Assets/Scripts/Controls.cs
> +            transform.position = new Vector3(transform.position.x, transform.position.y - FallingSpeed * Time.deltaTime, transform.position.z);
Исправил

2022-12-13 12:47 UTC, Demiurgosan commented on Assets/Scripts/Controls.cs
> +            if (transform.position.y < 0)
Исправил

2022-12-13 12:59 UTC, Demiurgosan commented on Assets/Scripts/Controls.cs
>      private void FixedUpdate()
Хотел использовать тот факт что он используется фиксированно раз за секунду. Ну просто. Исправил.

2022-12-13 13:32 UTC, Demiurgosan commented on Assets/Scripts/Player.cs
> +            _playerCubes[i+cubesCount].transform.position = new Vector3(transform.position.x, i + 0.5f + cubesCount, transform.position.z);
Добавил переменную CubeSize, как у стены. Ну так, наверно, понятнее что половина высоты куба-префаба используется.

2022-12-13 13:44 UTC, Demiurgosan commented on Assets/Scripts/UI_NextLvl.cs
> +public class UI_NextLvl : MonoBehaviour
Исправил

2022-12-13 13:44 UTC, Demiurgosan commented on Assets/Scripts/UI_NextLvl.cs
> +    public void OnBottonClick()
Исправил

2022-12-13 13:44 UTC, Demiurgosan commented on Assets/Scripts/UI_Restart.cs
> +    public void OnBottonClick()
Исправил

2022-12-21 18:52 UTC, Demiurgosan commented on Assets/Scripts/Lava.cs
> +            player.BumpedInLava();
Как по мне это нарушает единообразие. С лавой понятно, это простой сам по себе скрипт. Но если так делать, то чтобы сохранялась похожесть в взаимодействиях, нужно и просчёт взаимодействия стены переносить. И тогда, наверно, лучше отдельный скрипт "PlayerCollision", который будет принимать параметры от тех с кем столкнулся и обрабатывать их.

2022-12-21 19:00 UTC, Demiurgosan commented on Assets/Scripts/Player.cs
> +    private void OnDrawGizmos()
Исправил здесь и других скриптах.

2022-12-21 19:21 UTC, Demiurgosan commented on Assets/Scripts/Player.cs
> +            if (_rowsDenied[e] != 0) deniedRowsCount++;}
Нет, для идентификации какая строка "исключена" я использую значение внутри массива. Например в инспекторе у _rowsDenied по стандарту стоит 5 ячеек. Пользователь написал в 1ой - "3", во второй - "1". Все остальные остались "0".

2022-12-21 19:29 UTC, Demiurgosan commented on Assets/Scripts/Player.cs
> +        transform.position = new Vector3(transform.position.x, (float)columnBumpedMax, transform.position.z);
Исправил.

2022-12-21 20:21 UTC, Demiurgosan commented on Assets/Scripts/Player.cs
> +        GetComponent<Controls>().IsFall = true;
Исправил

2022-12-21 20:23 UTC, Demiurgosan commented on Assets/Scripts/UI_NextLvl.cs
> +        if(SceneManager.GetActiveScene().buildIndex == SceneManager.sceneCountInBuildSettings - 1)
Я сделал как в гдд было написано 3 уровня, скорее для примера. Да и попробовал, как оно работает через переключение сцен.

2023-01-12 11:11 UTC, Demiurgosan commented on Assets/Scripts/Wall.cs
>                  else if (player.transform.position.x < _wallPoints[e + 1])
Поправил. Вроде бы все случаи перекрывает.

2023-01-12 18:43 UTC, Demiurgosan commented on Assets/Scripts/Player.cs
> +        int deniedRowsCount = 0;
в старой книге читал что объявление через соответствующий тип (по сравнению с var) лучше тем, что позволяет подстраховаться от ошибок. это актуально? или же маловероятно встретить, поэтому лучше var для скорости? Просто я уже привык писать с конкретными типами.

2023-01-12 18:44 UTC, Demiurgosan commented on Assets/Scripts/Controls.cs
> +    [HideInInspector] public bool IsFall = false;
Резолвю потому что это относится к вопросу ниже.

2023-02-08 11:28 UTC, closed without merging